#---------------------------------#
#    environment configuration    #
#---------------------------------#
language: csharp
os:
  - linux
  - osx
sudo: required
dist: xenial
osx_image: xcode9.2 # OS X 10.12
dotnet: 2.2.105
mono: none

addons:
  apt:
    packages:
    - fsharp

before_script:
  - chmod +x build.sh
  - chmod +x -R /src
script:
  - travis_wait 60 ./build.sh