#---------------------------------#
#    environment configuration    #
#---------------------------------#
language: csharp
os:
  - linux
  - osx
sudo: required
dist: trusty
osx_image: xcode9.2 # OS X 10.12
mono: latest

addons:
  apt:
    packages:
    - fsharp

before_script:
  - chmod +x build.sh
script:
  - travis_wait 60 ./build.sh